name: uns-claudejp-600
services: {}
x-logging-default:
  driver: json-file
  options:
    compress: "true"
    labels: service,environment
    max-file: "3"
    max-size: 10m
    tag: '{{.Name}}/{{.ID}}'
x-logging-minimal:
  driver: json-file
  options:
    compress: "true"
    labels: service,environment
    max-file: "2"
    max-size: 5m
    tag: '{{.Name}}/{{.ID}}'
x-logging-verbose:
  driver: json-file
  options:
    compress: "true"
    labels: service,environment
    max-file: "5"
    max-size: 20m
    tag: '{{.Name}}/{{.ID}}'
